kind: Service
apiVersion: v1
metadata:
  name: cd-service-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    role: backend
    app: cd-service-app
